//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int id_answer { get; set; }
        public string Value_of_answer { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public int id_test { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
