//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constructor
    {
        public Constructor()
        {
            this.Cells = new HashSet<Cell>();
        }
    
        public int id_constructor { get; set; }
        public string type { get; set; }
        public string topic { get; set; }
        public string content { get; set; }
        public int id_statistic { get; set; }
        public int id_user { get; set; }
    
        public virtual ICollection<Cell> Cells { get; set; }
        public virtual Statistic Statistic { get; set; }
    }
}
