//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id_report { get; set; }
        public string link_doc { get; set; }
        public int id_statistic { get; set; }
        public int id_user { get; set; }
    
        public virtual Statistic Statistic { get; set; }
    }
}
