//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public Statistic()
        {
            this.Constructors = new HashSet<Constructor>();
            this.Reports = new HashSet<Report>();
        }
    
        public int id_statistic { get; set; }
        public Nullable<int> res { get; set; }
        public int id_user { get; set; }
    
        public virtual ICollection<Constructor> Constructors { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual User_of_labPI User_of_labPI { get; set; }
    }
}
